### ISSUE TITLE
Issue with integrating webtorrent with electron.

### ISSUE THREAD

**Issue by aszokalski** [webtorrent/webtorrent#1276]
**What version of WebTorrent?**
I tried using webtorrent v0.98.21 and webtorrent-hybrid v1.0.6.

**What operating system and Node.js version?**
I use OSX high sierra and node.js v8.9.4.

**What browser and version? (if using WebTorrent in the browser)**
Electron v1.7.11

**What did you expect to happen?**
I was expecting that if I copy the code working with node.js to electron it would work correctly but it didn't. 

**What actually happened?**

When I try to download torrents with regular webtorrent package nothing happens. When console log WebTorrent.WEBRTC_SUPPORT i get false (why? Electron has webrtc support. Ever one of your developers said it on some youtube video). So I import webtorrent-hybrid which enables webrtc in Node.js but I get this pop up.
`
Uncaught Exception:
TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at Object.exports.spawn (child_process.js:390:9)
    at spawn (/Users/adamszokalski/github/bitnet-app/node_modules/cross-spawn/index.js:17:18)
    at Daemon._startElectron (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:169:20)
    at new Daemon (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:60:13)
    at module.exports (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:25:10)
    at module.exports (/Users/adamszokalski/github/bitnet-app/node_modules/electron-webrtc/index.js:5:16)
    at Object.global.WRTC [as wrtc] (/Users/adamszokalski/github/bitnet-app/node_modules/webtorrent-hybrid/lib/global.js:13:14)
    at new Client (/Users/adamszokalski/github/bitnet-app/node_modules/bittorrent-tracker/client.js:70:55)
    at Discovery._createTracker (/Users/adamszokalski/github/bitnet-app/node_modules/torrent-discovery/index.js:161:17)
`

Seems like something is wrong in your scripts. (I made a new project and reinstalled everything but still same error). 

Help me. What did I miss? Should I install some drivers?

**Comment by feross** [comment]
Electron **renderer processes** have WebRTC support. But the **main process** has no chromium integration at all.

Also, you should use the `webtorrent` package, not `webtorrent-hybrid` since you want to use the WebRTC implementation from the JS environment.
