### ISSUE TITLE
Tracker announce causes chrome-extension to crash due to too many RTCPeerConnections construct

### ISSUE THREAD

**Issue by reisti** [webtorrent/webtorrent#1349]
**What version of WebTorrent?**
0.98.24

**What operating system and Node.js version?**
Windows 10. Node.js: v 8.10.0

**What browser and version? (if using WebTorrent in the browser)**
Chrome 65.
**What did you expect to happen?**
First of all, thank you for a really awesome package! I am trying to create a chrome-extension to explore the possibility of a distributed P2P-based certificate transparency log and have got this to work. The approach is that every time the user visits a new tab, some certain information regarding the tab should be fetched as a torrent or from server if the tab is currently unseeded and then seeded by the user. This works really well for a number of tabs (around 6), more tabs then that results in an error. 

Removing old torrents and on callback adding new and thus making sure i only have a maximum of around 6 torrents active at any given time does not fix the problem. I have viewed the sourcecode of Webtorrent and found that torrent.remove does indeed have the desired behaviour of also destroying all the peers.

**What actually happened?**
Not immeditially but always after some time (around 30-90 seconds) after exceeding 6 torrents, I get the following error. Notable is that if I open more than 6 tabs, and thus start to seed them, they are in fact seeded and other peers can come and get them. Until the trackers make an announce and the extension crashes. 

`Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections
    at new Peer (chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:19793:14)
    at WebSocketTracker._createPeer (chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:2121:14)
    at generateOffer (chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:2087:43)
    at WebSocketTracker._generateOffers (chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:2080:5)
    at WebSocketTracker.announce (chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:1769:10)
    at chrome-extension://opjhcaejljcceoepbhfbdegegedaeeap/bundle.js:1693:12`

I have done some reasearch to this before posting this issue, and these seemded the most relevant:
[Cannot create so many PeerConnections](https://stackoverflow.com/questions/49532939/how-to-clear-rtcpeerconnection-webrtc?noredirect=1&lq=1) - This error was fixed when setting the RTCPeerConnection to null which is in fact done in webtorrent at Peer.destroy which is done on torrent.remove.
[Too many RTC Peer Connections](https://github.com/webtorrent/webtorrent/issues/415) - Feross explained that many RTCPeerConnections are opened when the "RTC offers" generated by the extension are sent to the tracker servers.
[RTCPeerConnection limit](https://stackoverflow.com/questions/41194545/maximum-number-of-rtcpeerconnection?noredirect=1&lq=1) - As refered to here, the maximum number of RTCPeerConnections is 256 (without a source though). This is quickly hit when the RTC offers to the trackers are generated.

So my questions are;

- Why are this error throwed? What is the limit?
- How can i controll the amount of RTCPeerConnections that are created?
- How can I get RTCPeerConnections and destory them (can that even fix the problem?)
- Any thoughts on this at all...

**Comment by download13** [comment]
I've into this problem as well, but it was with only one torrent left open for more than 15 minutes or so.

**Comment by arnWolff** [comment]
I encounter same issue.
As i can test it, passing 'numwant' option to each tracker announce url help to mitigate this bug but better for sure would be to fix it in webtorrent source.

**Comment by feross** [comment]
Yeah, we ought to mitigate this directly in WebTorrent by reducing the peer connection timeout (so peers get destroyed faster) and lowering the default `numwant`.

A global resource limiter would also help, since right now the client has no way to know it's reaching the browser's limit. It'll just try to create peers whenever it wants to and will hit the limit. Related to #163.

**Comment by didlie** [comment]
Can you please specify the most recent previous release that didn't have this issue, and tell me how I can get an un-minified version of the build.

**Comment by chr15m** [comment]
I have some more data for this issue. As per original poster I'm also working with tabs connected to a single infoHash over long periods of time. I have `numwant=5` set.

Symptoms I am seeing:

 * In `chrome:webrtc-internals` up to 44 WebRTC connections getting created (see last screenshot).
 * The `chrome:webrtc-internals` tab crashing(!).
 * WebRTC connections remaining in that view long after the `simple-peer` debug messages say they have been destroyed.
 * `Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections`

Suspect not all references are getting cleaned up immediately. Could be Chrome being slow to garbage collect those resources.

Some screenshots over about an hour of testing:

### Start with `numwant` offers

![webrtc-1](https://user-images.githubusercontent.com/67130/44965000-fadac880-af65-11e8-9884-e38bfe877300.png)

### Quite quickly exceed `numwant` outstanding offers

![webrtc-2](https://user-images.githubusercontent.com/67130/44965001-fadac880-af65-11e8-9365-adf4991b2409.png)

### Many offers say they are closed but still appear

![webrtc-3](https://user-images.githubusercontent.com/67130/44965004-fadac880-af65-11e8-95ae-3c4d9c64a131.png)

### Chrome WebRTC internals tab crashes

![webrtc-4](https://user-images.githubusercontent.com/67130/44965005-fb735f00-af65-11e8-8d50-347ec13a509b.png)

### Number of offers continues to fluctuate reaching `44`

![webrtc-5](https://user-images.githubusercontent.com/67130/44965007-fc0bf580-af65-11e8-86a8-c0191ecdf902.png)
![webrtc-6](https://user-images.githubusercontent.com/67130/44965008-fc0bf580-af65-11e8-8718-98c147e82bb4.png)
![webrtc-7](https://user-images.githubusercontent.com/67130/44965009-fca48c00-af65-11e8-8119-5f61c1996bee.png)
![webrtc-8](https://user-images.githubusercontent.com/67130/44965011-fd3d2280-af65-11e8-989f-c933e59121a3.png)
![webrtc-9](https://user-images.githubusercontent.com/67130/44965012-fd3d2280-af65-11e8-94d7-d2808bab97cb.png)

Will continue to investigate.

**Comment by didlie** [comment]
I ran a test on Google Chrome and the maximum number of RTCPeerConnections is 499 before this error appears. So there is a fundamental problem with the peer creation process in webtorrent. It does not create peers in an efficient way. And, as you pointed out, the run-time of any browser instance of webtorrent is limited , as the maximum number of allowed RTCPeerConnection is capped at 499. Peer connections must be created efficiently, or the browser will crash with the error you see. I also had to implement a pre-validation process for peer handshakes to avoid the 499 RTCPeerConnection cap in Chrome.... other browsers also have limits, and MS Edge simply does not allow the creation of a raw dataChannel.... perhapse because data networking is a product MS sells.... but thats beyond the point. Feel free to message me for help on this issue. I spend several months developing an algorythm to create fully connected peer data networks using WebRTC and I succeeded. I published my solution on Amazon . You can google: Serverless Javascript Networking Algorithm , by Isaac Jacobs, to see the published Javascript code solution.

**Comment by arnWolff** [comment]
On https://github.com/Novage/p2p-media-loader , they use bittorrent-tracker and simple-peer for the p2p part of project. 
As i can test it on their demo website ( http://novage.com.ua/p2p-media-loader/demo.html ), there is no bug here. Any destroyed peer is correctly garbage collected in Chrome.
I don't have currently enough time to investigate it but could be a good starting point to fix this bug on Webtorrent.

**Comment by arnWolff** [comment]
Because this is still not (would it be?) fixed in Chromium, i finally use a workaround using ObjectURL and specifically the `revokeObjectURL` method which is the only method i know that can be used to invoke (in)directly Garbage Collector cycle. This is my current workaround:

```
queueMicrotask(() => { // || >> requestIdleCallback
  let img = document.createElement("img");
  img.src = window.URL.createObjectURL(new Blob([new ArrayBuffer(5e+7)])); // 50Mo
  img.onerror = function() {
    window.URL.revokeObjectURL(this.src);
    img = null
  }
})
```
This is my post on [SO](https://stackoverflow.com/questions/66546934/how-to-clear-closed-rtcpeerconnection). I'd be really glad to find any better way.
