### ISSUE TITLE
Can't install using "npm install webtorrent"

### ISSUE THREAD

**Issue by sg-s** [webtorrent/webtorrent#1498]
**What version of WebTorrent?**

current

**What operating system and Node.js version?**

OS: Ubuntu 17.10
node v6.11.4

**What browser and version? (if using WebTorrent in the browser)**

n/a

**What did you expect to happen?**

Tried 

```
npm install webtorrent

```

expected it to install

**What actually happened?**

did not install, got this error message instead:

```
> bufferutil@4.0.0 install /home/sgs/node_modules/bufferutil
> node-gyp-build

make: Entering directory '/home/sgs/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c:2:10: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
          ^~~~~~~~~~~~
compilation terminated.
bufferutil.target.mk:94: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/home/sgs/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sgs/node_modules/bufferutil
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:bufferutil@4.0.0 bufferutil@4.0.0 install: `node-gyp-build`
npm WARN install:bufferutil@4.0.0 Exit status 1

> utf-8-validate@5.0.1 install /home/sgs/node_modules/utf-8-validate
> node-gyp-build

make: Entering directory '/home/sgs/node_modules/utf-8-validate/build'
  CC(target) Release/obj.target/validation/src/validation.o
../src/validation.c:2:10: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
          ^~~~~~~~~~~~
compilation terminated.
validation.target.mk:94: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/home/sgs/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sgs/node_modules/utf-8-validate
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:utf-8-validate@5.0.1 utf-8-validate@5.0.1 install: `node-gyp-build`
npm WARN install:utf-8-validate@5.0.1 Exit status 1

```

**Comment by DiegoRBaquero** [comment]
The errors are not really webtorrent related. Seems like you are missing
some libs? And if suggests using node 8+

**Comment by sg-s** [comment]
thanks, using node v8 fixed this
