### ISSUE TITLE
Error: Request timed out

### ISSUE THREAD

**Issue by untitledlt** [webtorrent/webtorrent#1638]
Not sure what happened but 'metadata' event stopped firing and sometimes i'm getting `Error: Request timed out`. Torrent gets downloaded though.

How can I track down this problem and what exactly it is trying to reach when request timeout happens?

```javascript
Error: Request timed out
    at ClientRequest.req.on (/Users/******/node_modules/simple-get/index.js:67:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Socket._onTimeout (net.js:453:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

webtorrent version: 0.102.4
node version: v10.14.2
running on OS X

**Comment by SilentBot1** [comment]
Hi @untitledlt 

You can retrieve a more detailed set of logging from WebTorrent and it's accompanied modules by setting the environment variable `DEBUG` equal to the title of the specific module you would like logging from e.g. `DEBUG=webtorrent`, or an asterisk if you would like to retrieve logs from all modules e.g. `DEBUG=*`.

With this advanced logging, it should help us determine how and why WebTorrent is crashing when the request is timing out.

Just from a brief look at the stack trace, it appears that one of the `&xs=` servers within the MagnetURI is  possibly timing out causing the following error though the stack trace isn't very helpful.

To further look at the issue, we would need either the code to replicate the issue or the logs generated from setting the environment variable discussed above.

Kind regards
Brad
