### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by Senicolonna** [webtorrent/webtorrent#1795]
**What version of this package are you using?**
0.107.17
**What operating system, Node.js, and npm version?**
Ubuntu 16.04, NodeJS v8.17.0, NPM 6.13.4
**What happened?**
When i call the function "getBuffer" or "createReadStream", it throws an exception
**What did you expect to happen?**
It should download the files
**Are you willing to submit a pull request to fix this bug?**

When i run this

 torrent.on('done', function () {
        console.log('torrent download finished')
        torrent.files.forEach(function (file) {
            file.getBuffer(async function (err, buffer) {
                if (err) throw err
                await fs.outputFile(downloadPath + (downloadPath.endsWith('/') ? '' : '/') + file.path , buffer, 'binary')
            })
        })
    })
})

Happen this

/project/node_modules/webtorrent/lib/file-stream.js:59
      debug('read %s (length %s) (err %s)', p, buffer.length, err && err.message)
                                                      ^

TypeError: Cannot read property 'length' of undefined
    at _torrent.store.get (/project/node_modules/webtorrent/lib/file-stream.js:59:55)
    at /project/node_modules/fs-chunk-store/index.js:198:23
    at end (/project/node_modules/run-parallel/index.js:18:15)
    at done (/project/node_modules/run-parallel/index.js:22:10)
    at each (/project/node_modules/run-parallel/index.js:28:7)
    at /project/node_modules/run-parallel/index.js:43:37
    at /project/node_modules/fs-chunk-store/index.js:191:27
    at apply (/project/node_modules/thunky/index.js:44:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by guidouil** [comment]
IMHO the currently working version with multi files torrents is 0.104.0
I tried other versions on my project and the currently working whon't pass 0.105 don't know why but can see the results :)
