### ISSUE TITLE
ReferenceError: URL is not defined Error and process crashes

### ISSUE THREAD

**Issue by keshavbhatt** [webtorrent/webtorrent#1850]
**What version of this package are you using?**
webtorrent 0.108.1 , webtorrent-cli 3.0.5

**What operating system, Node.js, and npm version?**
Ubuntu Linux 20.04  Linux x64
node v8.17.0

**What happened?**
Trying to download torrent file and play it via mpv.
Gives error and process crashes with the following output
```
DEBUG INFO: webtorrent-cli 3.0.5, webtorrent 0.108.1, node v8.17.0, linux x64, exit 1
/home/bulld/node_modules/webtorrent/lib/server.js:79
    const pathname = new URL(req.url, 'http://example.com').pathname
                     ^

ReferenceError: URL is not defined
    at Server.onRequest (/home/bulld/node_modules/webtorrent/lib/server.js:79:22)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:660:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)

```
**What did you expect to happen?**
Download torrent and play file

**Are you willing to submit a pull request to fix this bug?**
No yet.

**Comment by keshavbhatt** [comment]
I upgraded node version and its works. Thanks
