### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#2063]
Error from WebTorrent Desktop telemetry (may already be fixed on `master`, unclear)

```
Processes: webtorrent, platforms: darwin linux win32, versions: 0.2.0 0.21.0 0.24.0
TypeError: Cannot read property 'length' of undefined
    at .../node_modules/webtorrent/lib/file-stream.js:59:55
    at .../node_modules/fs-chunk-store/index.js:199:23
    at end (.../node_modules/run-parallel/index.js:18:15)
    at done (.../node_modules/run-parallel/index.js:22:10)
    at each (.../node_modules/run-parallel/index.js:28:7)
    at .../node_modules/run-parallel/index.js:43:37
    at .../node_modules/fs-chunk-store/index.js:192:27
    at apply (.../node_modules/thunky/index.js:44:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by alxhotel** [comment]
Yep, I agree. This should already be fixed
