### ISSUE TITLE
Bug: Electron process exited with code 1

### ISSUE THREAD

**Issue by LoveIsGrief** [webtorrent/webtorrent#2230]
I wrote a [client to help reseed peertube videos](https://gitlab.com/NamingThingsIsHard/media_tools/peertube-reseed-js), but unfortunately I'm not able to get it to work because webtorrent just crashes before seeding can start.

 - "webtorrent": "^1.5.8"
 - "webtorrent-hybrid": "^1.0.6"

The project has a docker image that  recreates the problem. Run `docker-compose up prod`
```
prod_1  | 
prod_1  | > peertube-reseed-js@0.0.1 start
prod_1  | > ./index.js "https://tilvids.com"
prod_1  | 
prod_1  | Creating target directory /tmp/peertube-reseed/
prod_1  | /app/node_modules/simple-peer/index.js:129
prod_1  |       this._pc.peerIdentity.catch(err => {
prod_1  |                             ^
prod_1  | 
prod_1  | TypeError: Cannot read properties of null (reading 'catch')
prod_1  |     at new Peer (/app/node_modules/simple-peer/index.js:129:29)
prod_1  |     at WebSocketTracker._createPeer (/app/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:413:18)
prod_1  |     at generateOffer (/app/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:379:47)
prod_1  |     at WebSocketTracker._generateOffers (/app/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:372:7)
prod_1  |     at WebSocketTracker.announce (/app/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:63:12)
prod_1  |     at Socket.<anonymous> (/app/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js:44:14)
prod_1  |     at Object.onceWrapper (node:events:509:28)
prod_1  |     at Socket.emit (node:events:402:35)
prod_1  |     at Socket._handleOpen (/app/node_modules/simple-websocket/index.js:202:10)
prod_1  |     at WebSocket.Socket._ws.onopen (/app/node_modules/simple-websocket/index.js:77:36)
```

# Investigation

I tried modifying electron-eval ( in `node_modules`) to force starting electron without Xvfb (outside of docker) but it just failed. The test code from https://github.com/mappum/electron-eval works though :shrug:

**Comment by DiegoRBaquero** [comment]
This is an issue of `simple-peer`
