### ISSUE TITLE
Cannot get peer. Crashes application.

### ISSUE THREAD

**Issue by Ameliaaaaaaa** [webtorrent/webtorrent#2299]
**What version of this package are you using?**: 1.8.13

**What operating system, Node.js, and npm version?**: Ubuntu 20.04 LTS x64, Node v16.14.2, NPM v8.5.0

**What happened?**:
```
/root/App/node_modules/webtorrent/lib/torrent.js:954
    peer = this._peers[id]
TypeError: Cannot read properties of null (reading 'IP_ADDRESS:50065')
    at Torrent.removePeer (/root/App/node_modules/webtorrent/lib/torrent.js:954:23)
    at Peer.destroy (/root/App/node_modules/webtorrent/lib/peer.js:386:22)
    at Timeout.<anonymous> (/root/App/node_modules/webtorrent/lib/peer.js:347:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**What did you expect to happen?**:
Handled so it doesn't crash.

**Are you willing to submit a pull request to fix this bug?**: If I know how.

This started after I destroyed torrents once they were finished (keeping store)

**Comment by flyingspoon** [comment]
Bump!

Having the same issue:

```
/root/project/node_modules/webtorrent/lib/torrent.js:954
    peer = this._peers[id]

TypeError: Cannot read property 'IP_ADDRESS:30779' of null
    at Torrent.removePeer (/root/project/node_modules/webtorrent/lib/torrent.js:954:23)
    at Peer.destroy (/root/project/node_modules/webtorrent/lib/peer.js:386:22)
    at Timeout.<anonymous> (/root/project/node_modules/webtorrent/lib/peer.js:355:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
How can I handle it, are there any fixes or solutions?

**Comment by Ameliaaaaaaa** [comment]
It happens when you destroy the torrent. Only way I know of is not destroying the torrent

**Comment by flyingspoon** [comment]
For my use-case, I need to destroy the torrent sadly.
Is there no way to handle the error and after re-adding the torrent, maybe change peers for example, and if one is null, then change to one that is not null?

Hope someone can post a solution

**Comment by risharde** [comment]
This issue is still not fixed!!!

**Comment by flyingspoon** [comment]
> This issue is still not fixed!!!

Just throw it into PM2, whenever it crashes PM2will start it again. Even though it's not exactly a fix, it's better then having to manually restart your application. I doubt we will get a fix anytime soon.

**Comment by ThaUnknown** [comment]
this defo needs to be fixed by the community, as it only seems to happen on linux, and afaik none of the maintainers run linux
