### ISSUE TITLE
Webtorrent.add() should return the duplicate torrent instead of throwing error

### ISSUE THREAD

**Issue by resession** [webtorrent/webtorrent#2342]
**What version of this package are you using?**
1.8.24

**What problem do you want to solve?**
if there is a duplicate torrent that is already active, then `Webtorrent.add()` should return the duplicate torrent(just like `Webtorrent.seed()`), and not throw an error

**What do you think is the correct solution to this problem?**
need to get other people's opinion on this

**Are you willing to submit a pull request to implement this change?**
if it is not too difficult

**Comment by gmjimenezc** [comment]
Can I work on this?

**Comment by gmjimenezc** [comment]
@resession can you give me the steps to replicate the error?

**Comment by resession** [comment]
> @resession can you give me the steps to replicate the error?

```
Error: Cannot add duplicate torrent 0e0119015227367313ef6a57da7f388c185bf2f5
    at Torrent.onInfoHash (F:\Proj\Research\test\node_modules\webtorrent\index.js:288:28)
    at Object.onceWrapper (node:events:642:26)
    at Torrent.emit (node:events:527:28)
    at Torrent._onParsedTorrent (F:\Proj\Research\test\node_modules\webtorrent\lib\torrent.js:244:10)
    at F:\Proj\Research\test\node_modules\webtorrent\lib\torrent.js:214:14
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on WebTorrent instance at:
    at Torrent._destroy (F:\Proj\Research\test\node_modules\webtorrent\lib\torrent.js:764:21)
    at Torrent.onInfoHash (F:\Proj\Research\test\node_modules\webtorrent\index.js:288:19)
    at Object.onceWrapper (node:events:642:26)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by resession** [comment]
This has been fixed and merged

**Comment by resession** [comment]
This has been fixed and merged
