### ISSUE TITLE
Error REQUIRE_ESM

### ISSUE THREAD

**Issue by RfadnjdExt** [webtorrent/webtorrent#2472]
**What version of this package are you using?**
2.0.6

**What operating system, Node.js, and npm version?**
OS: Ubuntu 20.04.5 LTS 
Node.js: v19.5.0 
NPM: 9.3.1

**What happened?**
I'm using ts-node to run the code and typescript to import default export of webtorrent as WebTorrent but it return an error
```ts
@ ➜ (main) $ npx ts-node index.ts 
/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/webtorrent/index.js from index.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /node_modules/webtorrent/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/index.ts:6:38)
    at m._compile (/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/node_modules/ts-node/dist/bin.js:54:12)
    at main (/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

The code I'm using
```ts
import WebTorrent from 'webtorrent'

const client = new WebTorrent()
```

**What did you expect to happen?**
A successfully import
**Are you willing to submit a pull request to fix this bug?**
Maybe (?)

**Comment by RfadnjdExt** [comment]
> thus is a tsnode issue not webtorrent issue tbh

I see, maybe the v2 changes about changing to module type. Np, i'm using the mjs anyway. But i have a problem with torrent.createServer, it is undefined, should i create a new issues? Thanks

**Comment by ThaUnknown** [comment]
it changed in V2 read the docs
