### ISSUE TITLE
compile error 'importAssertions' isn't currently enabled

### ISSUE THREAD

**Issue by so010** [webtorrent/webtorrent#2504]
I'll try to get webtorrent v2 working in a typescript and react 18 environment.

**What version of this package are you using?**
2.0.15

**What operating system, Node.js, and npm version?**
debian 11
node 18.15.0
npm 9.5.0

**What happened?**
Compiled with problems:
ERROR in ./node_modules/webtorrent/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/stefan/src/webtorrent-react/node_modules/webtorrent/index.js: Support for the experimental syntax 'importAssertions' isn't currently enabled (21:35):

  19 | import { NodeServer, BrowserServer } from './lib/server.js'
  20 |
> 21 | import info from './package.json' assert { type: 'json' }
     |                                   ^
  22 | const VERSION = info.version
  23 |
  24 | const debug = debugFactory('webtorrent')

Add @babel/plugin-syntax-import-assertions (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-assertions) to the 'plugins' section of your Babel config to enable parsing.
    at instantiate (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:653:32)
    at constructor (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:947:12)
    at Parser.raise (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:3261:19)
    at Parser.expectPlugin (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:3300:16)
    at Parser.maybeParseImportAssertions (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:14152:12)
    at Parser.parseImport (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:14047:29)
    at Parser.parseStatementContent (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:12651:27)
    at Parser.parseStatementLike (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:12544:17)
    at Parser.parseModuleItem (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:12521:17)
    at Parser.parseBlockOrModuleBlockBody (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:13116:36)
    at Parser.parseBlockBody (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:13109:10)
    at Parser.parseProgram (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:12435:10)
    at Parser.parseTopLevel (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:12425:25)
    at Parser.parse (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:14245:10)
    at parse (/home/stefan/src/webtorrent-react/node_modules/@babel/parser/lib/index.js:14265:26)
    at parser (/home/stefan/src/webtorrent-react/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/home/stefan/src/webtorrent-react/node_modules/@babel/core/lib/transformation/normalize-file.js:64:38)
    at normalizeFile.next (<anonymous>)
    at run (/home/stefan/src/webtorrent-react/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/home/stefan/src/webtorrent-react/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/home/stefan/src/webtorrent-react/node_modules/gensync/index.js:261:32)
    at /home/stefan/src/webtorrent-react/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/stefan/src/webtorrent-react/node_modules/gensync/index.js:223:11)

**Comment by ThaUnknown** [comment]
Add @babel/plugin-syntax-import-assertions (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-assertions) to the 'plugins' section of your Babel config to enable parsing.
