### ISSUE TITLE
DOMException [AbortError]: This operation was aborted

### ISSUE THREAD

**Issue by uriva** [webtorrent/webtorrent#2874]
new error started appearing 

```
DOMException [AbortError]: This operation was aborted
    at new DOMException (node:internal/per_context/domexception:53:5)
    at AbortController.abort (node:internal/abort_controller:395:18)
    at Timeout._onTimeout (file:///node_modules/bittorrent-tracker/lib/client/http-tracker.js:17:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by uriva** [comment]
why would there be a DOMException on a nodejs app?

**Comment by SilentBot1** [comment]
@uriva this is from `@thaunknown/simple-peer` and the dependency `webrtc-polyfill`, which adds native bindings to libdatachannel in NodeJS. This is the part of WebTorrent which adds the ability to speed with WebRTC peers from NodeJS.

Are you able to provide the steps to replicate this?

**Comment by uriva** [comment]
maybe this will help?

```
process.on('SIGTERM', () => {
    client.destroy();
    process.exit(0);
});
```

**Comment by uriva** [comment]
This did not work, I think it's a real exception being thrown, just without any context, and it's an unhandled promise which causes my container to die.

**Comment by uriva** [comment]
I'm attaching the logs so it's is more clear:

```
2024-11-01 22:15:00.519 JST node:internal/per_context/domexception:53
2024-11-01 22:15:00.519 JST ErrorCaptureStackTrace(this);
2024-11-01 22:15:00.519 JST ^
2024-11-01 22:15:01.519 JST DOMException [AbortError]: This operation was aborted at new DOMException (node:internal/per_context/domexception:53:5) at AbortController.abort (node:internal/abort_controller:395:18) at Timeout._onTimeout (file:///node_modules/bittorrent-tracker/lib/client/http-tracker.js:17:16) at listOnTimeout (node:internal/timers:573:17) at process.processTimers (node:internal/timers:514:7)
2024-11-01 22:15:01.519 JST Node.js v21.3.0
2024-11-01 22:15:24.423 JST error Command failed with exit code 1.
2024-11-01 22:15:24.423 JST info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-11-01 22:15:30.569 JST Container called exit(1).
2024-11-01 22:15:32.107 JST Starting new instance. Reason: SCHEDULED - Instance started due to configured scaling factors (e.g. CPU utilization, request throughput, etc.) and their targets.
````

**Comment by uriva** [comment]
@ThaUnknown could it be that the timeout is fired before we enter the try/catch? in https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/client/http-tracker.js#L143?

**Comment by uriva** [comment]
I think it's an instance of this: https://github.com/nodejs/undici/pull/3354
Trying to upgrade my node version in hope it will solve it.

**Comment by uriva** [comment]
It's still happening, I suspect the bug exists in the version of `fetch` used here: https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/client/http-tracker.js#L4C20-L4C40

Would it be possible to remove this and use the native `fetch`?

**Comment by ThaUnknown** [comment]
that uses native fetch, undici is native fetch

**Comment by uriva** [comment]
In that case I have no idea what's going on, maybe the bug still exists in the version of node I'm using.

**Comment by uriva** [comment]
Yeah it seems the fix is only in unidici 7 alpha 2

Is it possible to change bittorrent-tracker to use this version?

It can take months or more until the fix arrives to node

**Comment by uriva** [comment]
Or simpler - use axios until it's fixed
