### ISSUE TITLE
Cannot read property 'peerPieces' of undefined

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent#919]
- WebTorrent version: 0.96
- Electron version: 1.4.0

From the desktop app telemetry:

```
Processes: webtorrent, platforms: win32, versions: 0.15.0
TypeError: Cannot read property 'peerPieces' of undefined
    at RarityMap.recalculate (...\node_modules\webtorrent\lib\rarity-map.js:107:30)
    at Torrent.RarityMap.self._onWire (...\node_modules\webtorrent\lib\rarity-map.js:15:10)
    at emitTwo (events.js:106:13)
    at Torrent.emit (events.js:191:7)
    at Torrent._onWire (...\node_modules\webtorrent\lib\torrent.js:1011:8)
    at Peer.onHandshake (...\node_modules\webtorrent\lib\peer.js:180:14)
    at Wire.onHandshake (...\node_modules\webtorrent\lib\tcp-pool.js:110:12)
    at Wire.g (events.js:286:16)
    at emitThree (events.js:121:20)
    at Wire.emit (events.js:194:7)
```

**Comment by dcposch** [comment]
@feross This error looks like it's new in the desktop app 0.15, so maybe it was introduced in a recent version of the library? (Or maybe we just happened to not run into it before.)

**Comment by feross** [comment]
Yeah, I was just about to open an issue for this too. Weird that it just started happening.
