### ISSUE TITLE
Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by davidgatti** [webtorrent/webtorrent#999]
Just so you know :) while downloading I got the following:

```
/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/webtorrent/lib/torrent.js:927
    self.client.emit('upload', uploaded)
               ^
TypeError: Cannot read property 'emit' of null
    at Wire.<anonymous> (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/webtorrent/lib/torrent.js:927:16)
    at emitOne (events.js:96:13)
    at Wire.emit (events.js:188:7)
    at Wire.piece (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/bittorrent-protocol/index.js:337:8)
    at respond (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/bittorrent-protocol/index.js:498:10)
    at /Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/fs-chunk-store/index.js:200:7
    at end (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/run-parallel/index.js:16:15)
    at done (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/run-parallel/index.js:20:10)
    at each (/Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/run-parallel/index.js:26:7)
    at /Users/davidgatti/Documents/GitHub/MrWhite/How-to-Stream-Torrents-in-NodeJS/node_modules/run-parallel/index.js:41:37
```

This happened after playing 2 weeks with this module, meaning it isn't frequent, but it did happen :)

* WebTorrent version: 0.98.0
* Node.js version: v6.4.0
* Browser name/version (if using WebTorrent in the browser): Using NodeJS module.

**Comment by feross** [comment]
I've seen this before too.
